### ISSUE TITLE
[Feature] Allow quickly setting a new wallpaper

### ISSUE THREAD

**Issue by Lucki** [ammargitham/WallFlow#10]
When using the automatic wallpaper there's currently no quick and easy way to refetch a new wallpaper if the current one doesn't fit your taste. Currently, this task needs navigating through several menu layers.

Some thoughts on how to accomplish this:
* A button widget to place on the home screen
* [Android Intents](https://developer.android.com/reference/android/content/Intent) which can be called from other applications. This would probably be a catch-all for every automation need out there.

**Comment by ammargitham** [comment]
Instead of a button widget, I can look into adding a Quick Settings tile and also an intent to allow triggers.

**Comment by Lucki** [comment]
Sure! Whatever you see fitting the most. :)

**Comment by Lucki** [comment]
Works wonderfully, thanks alot!

(Tested the quick settings tile only)
