### ISSUE TITLE
status of the project

### ISSUE THREAD

**Issue by personaingrata** [ammargitham/WallFlow#100]
it's been over a half year since you were last active on github. your last commit was in May 2024.

i would like to know about the status of the project and if you're going to maintain WallFlow again.

i hope you are doing well @ammargitham

**Comment by ammargitham** [comment]
Hey. I am doing fine. It's just that I have been busy with life and work. I have not abandoned this app. I do plan to get back to it. If things go well, I may start working on it sometime in January.

**Comment by personaingrata** [comment]
that's great news. thanks for the quick response

**Comment by LbsLightX** [comment]
**Your Last Commit Was In May 2024🫠**

Don’t tell me you’ve abandoned this project. I really love this app. I truly hope you bring it back and start working on it again. ♥️

**Comment by maki40681** [comment]
~~Downloads stopped working recently~~
Downloads are working. Had to reconfigure directory
No other forks have continued to be maintianed 🥲
