### ISSUE TITLE
[Bug] Wallpaper apply crash on Android 13 MIUI 14

### ISSUE THREAD

**Issue by ansarimohammed422** [ammargitham/WallFlow#12]
The app crashes when applying a local wallpaper
And suddenly closes itself.

My device is running on android 13 miui 14

**Comment by ammargitham** [comment]
@ansarimohammed422 and @Agi0m Can you test this debug build? 
It will be installed as a separate app. 
So the prev installed app won't be affected. Use the app with (Debug) in the name after install.
Had to zip it as Github does not allow uploading apk.

[app-base-debug.zip](https://github.com/ammargitham/WallFlow/files/12660568/app-base-debug.zip)

**Comment by Agi0m** [comment]
Can confirm it works.
Just some of the smoothness it gone it feels lags a little but if it's fixed than it's great.

**Comment by ammargitham** [comment]
Thanks for checking. The lag is due to it being a debug build. Release should be fine.

**Comment by ammargitham** [comment]
@ansarimohammed422 I'll wait till tomorrow for your confirmation before doing a release.

**Comment by ansarimohammed422** [comment]
Yes this debug build doesnt have that issue i can also confirm

Thanks.
