### ISSUE TITLE
[Feature] Option to Sort and Filter Local wallpapers  also

### ISSUE THREAD

**Issue by ansarimohammed422** [ammargitham/WallFlow#15]
Just like online wallpapers can you give sort and filter functionality to Local wallpaper section also

Like sort by date added in that local directory
Etc.

**Comment by ammargitham** [comment]
Sort by timestamp is possible. But in what way do you want to filter the local images?

**Comment by ansarimohammed422** [comment]
Like the ones i have downloaded just now should be on the top

**Comment by ammargitham** [comment]
That would get covered under sorting. I assumed that by filter you meant searching.

**Comment by ansarimohammed422** [comment]
Oh then it needs sorting
Thanks for correcting me

**Comment by ammargitham** [comment]
Available in [v1.5.0](https://github.com/ammargitham/WallFlow/releases/tag/v1.5.0)
