### ISSUE TITLE
"Apply wallpaper", "download" and "share" buttons don't work with images from Reddit

### ISSUE THREAD

**Issue by Fxsch** [ammargitham/WallFlow#26]
When I press it, nothing happens

**Comment by Fxsch** [comment]
I just tested a little and the `share` and `download` buttons don't work either. This issue also only happens with Reddit images, it works just fine on images from Wallhaven. I'll edit the title accordingly.

**Comment by ammargitham** [comment]
Fixed in v2.1.0
