### ISSUE TITLE
Image viewer buttons keep disappearing after zooming in

### ISSUE THREAD

**Issue by Fxsch** [ammargitham/WallFlow#27]
When the image has been zoomed in (even if you zoom back out), the buttons can't be used anymore because they keep on disappearing.

https://github.com/ammargitham/WallFlow/assets/77849217/24f6afd3-6cfd-48b9-96f9-13f3a97935e2

**Comment by ammargitham** [comment]
@Fxsch Does this happen every time? I can't seem to reproduce on my device.

**Comment by ammargitham** [comment]
Which phone are you using?

**Comment by Fxsch** [comment]
Just tried it on my brothers phone as well and the issue was there too

**Comment by personaingrata** [comment]
i have the same issue, WallFlow version 2.0 but previous versions had this bug too.
it happens every time and zooming out again doesn't recover the bottom bar. to recover i swipe WallFlow away and bring it back to foreground, it also recovers when i swipe back to the picture overview and open the picture again, but as soon as i zoom the bug repeats.

phone is a Pixel 6, GrapheneOS, Android 14


https://github.com/ammargitham/WallFlow/assets/54642064/eac0dc54-def3-4b80-94c6-d44085533e31

**Comment by ammargitham** [comment]
Okay, so to workaround this problem, I am removing auto hiding when image is transformed. It will only hide if tapped. Let me know if this fixes this issue.

**Comment by ammargitham** [comment]
Addressed in v2.1.0

**Comment by ammargitham** [comment]
@Fxsch @personaingrata So is this issue resolved in v2.1.0?

**Comment by Fxsch** [comment]
Yes, it is. Thanks.

**Comment by personaingrata** [comment]
fixed!

thank you
