### ISSUE TITLE
[feature request] nice to have features

### ISSUE THREAD

**Issue by personaingrata** [ammargitham/WallFlow#29]
thanks for developing WallFlow, i appreciate the effort you put into the app.

i'm a long time "Aurora Wallpapers" user but it's development ceased long time ago and WallFlow is a great candidate to replace it.

i have some feature suggestions:
- [x] avoid redownloading the picture, when saving the picture (currently WallFlow downloads the picture twice. download when picture opened (if not in cache) and then download the picture again when the user saves the picture to disk.) (https://github.com/ammargitham/WallFlow/commit/5d615f18a42113ce6994b6514982d87d4e79d6c9)
- [x] show picture URL on the Info screen (https://github.com/ammargitham/WallFlow/commit/d3c8ac4f0b5fb750be544dc0cca93d30b9a41363)
- [x] copy a tag to clipboard when long pressed (https://github.com/ammargitham/WallFlow/commit/01a86934d8534a9ebbe52f951191715a7a2375c1)
- [x] add another favourites button to the bottom bar (https://github.com/ammargitham/WallFlow/issues/28)
- [x] ~~show picture view count and resolution on the pic overview~~ some kind of indicator if i already viewed a picture (https://github.com/ammargitham/WallFlow/commit/2ee7b9b70a4c5911d4c0e1064f56ab0d0ea93b5a)
- [x] add the tags as exif metadata (without deleting other exif metadata the picture might hold) when saving the pic to disk (https://github.com/ammargitham/WallFlow/commit/7c4671e3604e864aab12ce4dd0edcf582223f5b0)

**Comment by ammargitham** [comment]
Hey @personaingrata Thanks for the suggestions.

> add another favourites button to the bottom bar
Already added in #28 

>show picture view count and resolution on the pic overview
Resolution is already shown in info. For view count, I assume you mean viewed by you? If so, I can look into adding that.

> add the tags as exif metadata (without deleting other exif metadata the picture might hold) when saving the pic to disk
As far as I can find online, the only place to store this in exif would be `UserComment`. Can you tell me how do you intend to use this data?

For others I will implement them in future commits.

**Comment by personaingrata** [comment]
> add another favourites button to the bottom bar 

thanks for fixing the bottom bar and the extra favourites button and being open for suggestions!


> Resolution is already shown in info. For view count, I assume you mean viewed by you? If so, I can look into adding that.

resolution in info is fine, i think otherwise it would clutter the overview.
for the view count i meant the overall view count from all users (wallhaven) but it would also be nice to have some kind of indicator if i already viewed a picture. that's useful when sorting via date added/descending.


> As far as I can find online, the only place to store this in exif would be UserComment. Can you tell me how do you intend to use this data?

the exif data is useful for quickly searching through a local archive for a given tag.

**Comment by ammargitham** [comment]
> for the view count i meant the overall view count from all users (wallhaven)

This would require a central server plus tracking which I will not implement.


>  it would also be nice to have some kind of indicator if i already viewed a picture

This is something I can look into implementing

> the exif data is useful for quickly searching through a local archive for a given tag

So, is the UserComment sufficient for you?

**Comment by personaingrata** [comment]
> This would require a central server plus tracking which I will not implement.

this must be a misunderstanding, with view count i meant the views which are already tracked by wallhaven and is shown on the info page. i'm not talking about any additional tracking, please no.

> This is something I can look into implementing

that's a big plus in my book!

> So, is the UserComment sufficient for you?

the UserComment field would be my choice too  and it's easily editable by many image viewers.

**Comment by ammargitham** [comment]
> with view count i meant the views which are already tracked by wallhaven and is shown on the info page

Actually that's just the count returned from the wallhaven api response nothing the app tracks.

> the UserComment field would be my choice too and it's easily editable by many image viewers.

Great, will implement that too (as a setting needing to be enabled).

**Comment by personaingrata** [comment]
> Actually that's just the count returned from the wallhaven api response, nothing the app tracks.

i never claimed anything else. just that it might be useful to expose the count on the picture overview screen too.

> Great, will implement that too (as a setting needing to be enabled).

great, exif tag passthrough is coming.

thanks in advance

**Comment by ammargitham** [comment]
Requested features are implemented, check 1st post for the related commits. Unreleased features will be available in the next release.

**Comment by ammargitham** [comment]
All features released in v2.2.0

**Comment by personaingrata** [comment]
that's great news! i had a quick look at wallflow 2.2.0 it's all working well!
by looking at the commits it seems like the tags2exif and the viewed indicator haven been quite a bit of work.

thank you for the enhancements, i appreciate it
