### ISSUE TITLE
sorting bug

### ISSUE THREAD

**Issue by personaingrata** [ammargitham/WallFlow#30]
when sorted via date added --> order descending it's sometimes possible that newly added pictures get sorted after older pictures, swiping down to refresh and cleaning cache doesn't fix this

WallFlow 2.1.0 but this bug was present in previous versions too

**Comment by ammargitham** [comment]
If you use the staggered grid layout, the one where images are sized according to their resolution, the AndroidX grid component tries to fit them as per available space. Due to this it moves around images to the place where it would correctly fit. So some images may appear before others.

This could be the problem you are facing.

**Comment by personaingrata** [comment]
i'm not sure if this is the grid component conflicting with user settings but if i set "show me the latest pics first" i want so see the latest uploads first. otherwise what's the point of the user set sort order?
my initial report was based on the staggered layout, but i've set it to fixed and by chance i ran into the issue again. just to clarify, this not always happening with new uploads, but it's happening often. i recorded my screen and please excuse, i compared it to aurora wallpapers just to show you the difference in sorting, both apps use the wallhaven api and both apps are set to "show latest first"
the image WallFlow shows first, is a pic you've already seen on another bug report from me a day ago or so, but there's already new uploads which the other app sorts correctly (in this case it's a picture with green leaves). when refreshing WallFlow you can see that the app is attempting to sort them right on the top, but it fails. WallFlow's layout is set to fixed and not the default staggered.

i hope you can follow my explanation and the recording is of any use to you to hunt this down

https://github.com/ammargitham/WallFlow/assets/54642064/f6a57402-9bb7-4150-885e-a4813ffdf09e

**Comment by ammargitham** [comment]
Thanks for the video. I think I know what the problem is. Will look into fixing it.

**Comment by personaingrata** [comment]
nice, looking forward to it

**Comment by ammargitham** [comment]
Released in v2.2.0
