### ISSUE TITLE
searching for tags doesn't find all

### ISSUE THREAD

**Issue by personaingrata** [ammargitham/WallFlow#31]
when i'm on the info screen and tap on a tag, WallFlow doesn't list all pics with a given tag.

WallFlow 2.1.0

**Comment by ammargitham** [comment]
Can you give an example where this occurs?

**Comment by personaingrata** [comment]
i mean it's simple, tapping on a image tag doesn't find/show all pics with the same tag, sometimes it's showing nonen even though there's plenty images with the same tag, which another app correctly shows and probably the wallhaven.cc website too, but i didn't verify that.

if desired i can record my screen when i find the time and show you what i mean, atm i'm short on time.

thanks and have a nice weekend!

**Comment by ammargitham** [comment]
Hey, it could be that the filter settings are filtering the images out? Once you tap on a tag, check the filter settings by clicking the funnel icon as shown below:

![image](https://github.com/ammargitham/WallFlow/assets/8017365/5e40f593-712c-447a-a5cb-8559e4710f71)

**Comment by personaingrata** [comment]
i digged into this and i couldn't make a sense out of it, why WallFlow filters matching tags out and others not, then figured i only get SFW matches presented and the filter settings which i set are not respected. now there's another filter funnel in the search bar which btw is NOT provided when tappping a tag from a picture info screen. i only see the filter funnel i search directly from the overview screen. now everything makes perfectly sense and it's just confusing.

scenario 1:
set filters with NFSW content on the main lower filter funnel.  (search bar filter untouched/default)
tap a pic - tap info - tap a tag - results get filtered with the filter settings from the search bar applied.
expected behaviour: main filter settings are from applied to the tag search

scenario 2:
set filters with NFSW content on the main lower filter funnel. set search bar filter with NSFW content, don't save the search filter. swipe, tap the search bar filter funnel again and make sure NSFW is still set.
tap a pic - tap info - tap a tag - NSFW results are filtered out, the filter settings in the search bar were reset to default ---> NSFW unset.. seriously?

there should be other scenrios too, but i gave you two scenarios which you can quickly reproduce.

**Comment by ammargitham** [comment]
> main filter settings are from applied to the tag search

Actually both filters are kept separate because you may want very fine tuned home filters to control the home results (eg. included/excluded tags, resolutions, etc.). But when searching for something, it is usually expected to be without those filters and just give results relevant to the query. So that part will not change.

> tap a pic - tap info - tap a tag - NSFW results are filtered out, the filter settings in the search bar were reset to default

That's because each tap starts a new search currently. So the filters are reset. But I see that it can be cumbersome, to set the search filters again after the initial search.

To remedy this, I think I can do 2 things.

1. Keep the search filter button same place as the home filters button
2. Remember the search filters when changed

**Comment by personaingrata** [comment]
> Actually both filters are kept separate because you may want very fine tuned home filters to control the home results (eg. included/excluded tags, resolutions, etc.). But when searching for something, it is usually expected to be without those filters and just give results relevant to the query. So that part will not change.

my usage pattern is/was different, i was always using the home filter for searching individual stuff on the other app. WallFlow provides the ability to save filter settings and i appreciated that to save and restore filter settings, this was sufficient for me.

 what do you think about:
- simplifying the code and abandon the search filter settings to just have 1 central filter
or
- give the search it's own page and button and let the filter settings on the active screen apply by default?

**Comment by ammargitham** [comment]
Hey, I've started working on this. As for your suggestions:

>  simplifying the code and abandon the search filter settings to just have 1 central filter

The problem with this is again what I previously mentioned about home filters being fine tuned and search filters being relaxed. Also avoid the scenario if the user has excluded a tag in the home filter and tries to search the same filter. So keeping it separate is better. I'll just implement the feature of the search filters being remembered next time.

>  give the search it's own page and button and let the filter settings on the active screen apply by default?

This will be a big undertaking, and I'd rather keep it simple for now. If maybe in the future there are more requests for a separate search screen, then I'll think about implementing it.
