### ISSUE TITLE
WallFlow Plus cannot download wallpapers on Motorola moto e7 (Android 10)

### ISSUE THREAD

**Issue by kjhota123** [ammargitham/WallFlow#34]
WallFlow Plus is failling to download the wallpapers, both automatically through auto wallpaper and manually.

My phone is a Motorola moto e7 running Android 10, I have tried setting and removing the directory multiple times (internal storage and SD card), and yet nothing shows up on the folder.
I have no real experience with debugging or developing Android apps but I downloaded Android Studio to see if it can help in any way by attaching it to my physical phone through USB debugging.

Here is the Logcat before manually downloading a wallpaper of a Rubik's cube;
[2023 11 07 17 18 36 466.txt](https://github.com/ammargitham/WallFlow/files/13288625/2023.11.07.17.18.36.466.txt)

Here is the Logcat after I tapped Android's "Home" button and launched the app again after it was already running in the backgroud;
[2023 11 07 17 25 31 794.txt](https://github.com/ammargitham/WallFlow/files/13288633/2023.11.07.17.25.31.794.txt)

**Comment by ammargitham** [comment]
Thanks for the report. Seems it was a problem specifically for Android 10. Will be fixed in the next version.

**Comment by ammargitham** [comment]
Released in v2.2.0

**Comment by kjhota123** [comment]
Unfortunately, the issue only seems to be partially fixed.
 I have set the download location to;
 
"/storage/emulated/0/WallFlow", 

But the wallpapers are actually going to; 
"/storage/emulated/0/**Download**/WallFlow

**Comment by ammargitham** [comment]
@kjhota123 The app downloads the wallpaper in the 'Wallflow' directory in the downloads folder provided by the os.

> I have set the download location to;
>"/storage/emulated/0/WallFlow",

How did you set that? The app does not have any setting to change the download location.

**Comment by kjhota123** [comment]
I wanted the app to download the wallpapers under Android's default internal storage directory, so I simply created a new folder called "WallFlow" inside of it.

1. I went to the app, tapped on the "`Local`" button located at the bottom,
2.  Then on the "`+ Add Directory`" button in the middle of the screen,
3.  Google's default file picker Documents UI (com.google.android.documentsui) shows up.
4. I tap on the internal storage, scroll down to find the WallFlow folder I just created.
5. Tap Documents UI "`USE THIS FOLDER`" button
6. The WallFlow app goes back to the Manage Local menu, and done.

https://github.com/ammargitham/WallFlow/assets/12678021/d3f3a9dc-46f8-4833-bd67-1ea13e33c708

**Comment by ammargitham** [comment]
You misunderstood the use of the local tab. It's used to show any images you may have in local folders. And you can use those images in the auto wallpaper settings. That is why you can add more than one folder in the local tab.

It does not mean that the wallpapers will be downloaded to the folders selected in that tab.

**Comment by ammargitham** [comment]
If you want the feature to change the download location, you can create a new feature request.
