### ISSUE TITLE
Auto wallpaper doesnt change without notification 

### ISSUE THREAD

**Issue by Warden20** [ammargitham/WallFlow#37]
When I dont have thw notification toggle enabled the wallpaper doesnt change. This happens with reddit, wallahavrn, favorities and local

**Comment by ammargitham** [comment]
Does it change when you click "Change Now"?

**Comment by ammargitham** [comment]
I can't seem to reproduce it. Did you change constraints for auto wallpaper?

**Comment by Warden20** [comment]
![Screenshot_20231115-224951_WallFlow Plus](https://github.com/ammargitham/WallFlow/assets/64172827/247c2472-a90c-4fee-aeff-7320d316909f)
This are my settings

**Comment by ammargitham** [comment]
Hey, can you let me know if you changed anything under the 'Constraints' setting.

**Comment by ammargitham** [comment]
Also, can you tell me which phone is this?

**Comment by Warden20** [comment]
I reinstalled the app and the problem  fixed it selft

**Comment by ammargitham** [comment]
Ok, so I'll close this issue. Feel free to re-open if you face this again.
