### ISSUE TITLE
[Feature] Add target preference to auto wallpaper

### ISSUE THREAD

**Issue by Wjxfi** [ammargitham/WallFlow#4]
possibility not to apply wallpaper in phone lock mode, before I enter the password or unlock the phone. it's for privacy. Some people don't need to know about my wallpaper.

p.s. thank you so much for the best wallpaper app ever, but these features are absolutely needed

**Comment by ammargitham** [comment]
Do you mean not to change the lockscreen wallpaper using auto wallpaper?
