### ISSUE TITLE
Reproducible build failed

### ISSUE THREAD

**Issue by linsui** [ammargitham/WallFlow#44]
[com.ammar.wallflow.plus.zip](https://github.com/ammargitham/WallFlow/files/13539439/com.ammar.wallflow.plus.zip)

We have saw similiar issues on other apps. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138.

**Comment by ammargitham** [comment]
Hi. Thanks for the notification. I was aware of the failure and was trying to debug the cause the whole day. Will share my findings in the thread.

**Comment by ammargitham** [comment]
Fixed in v2.2.1
