### ISSUE TITLE
[Bug] Wallpapers do not maintain screen orientation 

### ISSUE THREAD

**Issue by Warden20** [ammargitham/WallFlow#45]
The wallpapers change position or orientation, it is as if the image is zoomed. It happens when I'm watching a video on youtube or any other application that I'm watching in full screen (horizontal orientation).

**Comment by ammargitham** [comment]
How the wallpaper is set in different orientations is handled by the OS or launcher. Not sure what the app can do about it.

**Comment by ammargitham** [comment]
@Warden20 As mentioned above, I don't think this is a bug with the app, so I am closing this issue. If I have misunderstood your issue, then please reopen with some more details.
