### ISSUE TITLE
(Bug) Can not add `r/MobileWallpaper` subreddit

### ISSUE THREAD

**Issue by cyberboh** [ammargitham/WallFlow#46]
As I write in tittle I can not add spesific subreddit
It becomes error like this

https://i.postimg.cc/TPMFSxvZ/Screenshot-20231205-104006-com-ammar-wallflow-plus.jpg

**Comment by ammargitham** [comment]
Seems you may have added a space after 'Mobile'.

**Comment by James-Willer** [comment]
For me on a Samsung phone, it was the autocorrect from the keyboard changing it when I press space, that might be ur case too.
I suggest clicking on kpics in the suggestion menu of ur keyboard.
