### ISSUE TITLE
Feature Request: Light and Dark wallpapers

### ISSUE THREAD

**Issue by srfsh** [ammargitham/WallFlow#49]
It'd be nice if the app allowed to mark some wallpapers to be used during light mode, dark mode, and maybe even when Extra Dim is on (which is available on android 12+), and auto-rotate the wallpapers that are marked within the current mode.

This might be more complicated than one might think (in terms of combinations, of course).  For instance, one might wanna use a wallpaper for light mode OR dark mode, independently of Exra Dim, as well as when Extra Dim AND dark mode, or only Extra Dim is on, independetly of dark or light mode.  These are to take into account.

Thanks for the app!

**Comment by ammargitham** [comment]
Sounds like a nice feature to have. I will discuss more once I get to this.

**Comment by ammargitham** [comment]
Regarding the extra dim setting, would it be used only with dark wallpapers?
Like if the extra dim is on with the light mode, do you want mark light wallpapers separately for those?

**Comment by srfsh** [comment]
> Regarding the extra dim setting, would it be used only with dark wallpapers?
> Like if the extra dim is on with the light mode, do you want mark light wallpapers separately for those?

I would highly believe that no one would ever want to use extra dim with light mode.  I let you decide, though.  If it's simpler without that combination, I'd say do it without.

**Comment by ammargitham** [comment]
I'll add a checkmark for extra dim only when the user marks the image as dark.

> one might wanna use a wallpaper for light mode OR dark mode, independently of Exra Dim, as well as when Extra Dim AND dark mode, or only Extra Dim is on, independetly of dark or light mode

As for this, I have to revamp how the sources are set for each target (lock or home screen). I think I will work on #51 along with this. But I am traveling starting next week for a month, so progress will be slow.

**Comment by srfsh** [comment]
Sounds nice.  Wish you a great journey!
