### ISSUE TITLE
[Feature] Backup settings, favorites and saved searches

### ISSUE THREAD

**Issue by Wjxfi** [ammargitham/WallFlow#5]
backup your settings and, most importantly, your bookmarks and saved searches to a file with the possibility of exporting and importing them back into the application. my phone might break, I'm scared. Also, to synchronize between phones

p.s. thank you so much for the best wallpaper app ever, but these features are absolutely needed

**Comment by ammargitham** [comment]
Yes, I will add the feature to export/import settings, favorites and saved searches to/from a file. Maybe you could then use some other service to backup the file/folder and sync between phones.

**Comment by ammargitham** [comment]
This feature will be in the next release. Currently it is manual. Scheduled backup feature will be added later.
