### ISSUE TITLE
Ability to set different catalogues for home and lock screen

### ISSUE THREAD

**Issue by ViktorKahu** [ammargitham/WallFlow#51]
As the title says.

I woild like to be able to  use one collection for the home screen and another collection for the lock screen.

They could be:

- two different local folders
- one local folder and one online source
- two different online sources
- one local folder and one favorites folder
- etc... you get the idea.

**Comment by beast-14** [comment]
Upcoming in 2.3.0

**Comment by ViktorKahu** [comment]
I'm guessing this isn't planned and project is abandoned.

**Comment by ammargitham** [comment]
Not at all. I was on vacation the entire month of January. I am currently working on #49 and this issue together.

**Comment by ViktorKahu** [comment]
Thank you so much, works beautifully!
