### ISSUE TITLE
Auto wallpaper bug

### ISSUE THREAD

**Issue by beast-14** [ammargitham/WallFlow#52]
I am trying to change my auto wallpaper but some wallpapers are applying like this I am sending the SS

![Screenshot_20231226-175304_crDroid Home.png](https://github.com/ammargitham/WallFlow/assets/145965285/e53ed474-4a1f-428c-9672-961a215806f0)

![Screenshot_20231226-175300_WallFlow Plus.png](https://github.com/ammargitham/WallFlow/assets/145965285/8f98d664-9cc8-4611-86f7-75d9d7955eb3)

**Comment by beast-14** [comment]
I tried everything in my knowledge.. tell me if I am doing something wrong

**Comment by ammargitham** [comment]
Did you disable crop for auto wallpaper? What happens if you manually apply the same wallpaper?

**Comment by ammargitham** [comment]
> Yes I tried disabling crop but it's still there

I'm wondering if you disabled the crop option in the auto wallpaper settings. This could be the result of that.
Is the below option enabled or disabled?
![Screenshot_20231226_220042](https://github.com/ammargitham/WallFlow/assets/8017365/77c3d752-04a2-4cbb-bf36-88ddf3b5acc9)

**Comment by beast-14** [comment]
> > Yes I tried disabling crop but it's still there
> 
> I'm wondering if you disabled the crop option in the auto wallpaper settings. This could be the result of that.
> Is the below option enabled or disabled?
> ![Screenshot_20231226_220042](https://github.com/ammargitham/WallFlow/assets/8017365/77c3d752-04a2-4cbb-bf36-88ddf3b5acc9)
> 
> 

Sir it's disabled 
![Screenshot_20231226-183359_WallFlow Plus.png](https://github.com/ammargitham/WallFlow/assets/145965285/e2e4df78-727f-4797-adc1-e3d1f40a1445)

**Comment by ammargitham** [comment]
Got it. Thanks. Can you provide me the source url of the image? You can find it in the info sheet. Keep the crop on until I fix it.

**Comment by beast-14** [comment]
> Got it. Thanks. Can you provide me the source url of the image? You can find it in the info sheet. Keep the crop on until I fix it.

Sir it's from local storage, as I have a complete collection of wallpaper offline and I wanted that to change automatically according to my preferences.

**Comment by ammargitham** [comment]
> it's from local storage

Can you upload the image here? It will be helpful for my testing.

**Comment by beast-14** [comment]
> > it's from local storage
> 
> Can you upload the image here? It will be helpful for my testing.

Yes sir, here it is

![amw_prime (5).jpg](https://github.com/ammargitham/WallFlow/assets/145965285/8e0f5575-093c-4bd5-b794-2bcb6f418a2e)

**Comment by beast-14** [comment]
And thank you very much 😊

**Comment by beast-14** [comment]
> Did you disable crop for auto wallpaper? What happens if you manually apply the same wallpaper?

Sir, I figured something, it's happening mostly when I tap change now from settings and change wallpaper toggle from toggle in quick settings.

**Comment by KAGEYAM4** [comment]
Could it be `Object Detection` at fault?

**Comment by beast-14** [comment]
> Could it be `Object Detection` at fault?

Tried disabling it and also tried the apk without object detection (not plus) the problem was still there

**Comment by KAGEYAM4** [comment]
i just tested it, same thing on my end too

**Comment by ammargitham** [comment]
Fetching local image resolution using Exif data was not working for this image, and maybe other local images too. So I changed how the resolution is fetched. This may lead to a bit slower listing of the images in the 'Local' tab but at-least the resolution will be correct.

**Comment by ammargitham** [comment]
Fixed in v.2.3.1

**Comment by beast-14** [comment]
> Fixed in v.2.3.1

This app is my favorite now 🥰

**Comment by beast-14** [comment]
> Fixed in v.2.3.1

Bro .. I was using my phone and according to timer wallpaper changed.. but somehow the issue came again and I tried to put that specific picture in a different folder and changed it via toggle but issue was not there
Though I have no problem clicking the toggle but I am just letting you know

**Comment by ammargitham** [comment]
Ok, will try to debug it. Are you sure it was the same bug with the same photo?

**Comment by beast-14** [comment]
> Ok, will try to debug it. Are you sure it was the same bug with the same photo?

Not with the same photo but with these 2 photos 
![amw_prime (65).jpg](https://github.com/ammargitham/WallFlow/assets/145965285/af5b9397-18f5-4b81-8463-f4d7cbd234d5)

![amw_prime (80).jpg](https://github.com/ammargitham/WallFlow/assets/145965285/aaac9f97-930a-406b-8b16-c2395ad7ec1d)

I don't actually know what happened I was watching video and the app changed wallpaper in the background and it was buggy but when I put these 2 photos in different folder and waited for timer to change it automatically it was ok no problem.. then I checked using toggle and quick settings tile too .. no problem again .. could it be that I updated the app instead of reinstalling it .. but after that I didn't get any buggy wallpaper so I guess that's a win ☺️

**Comment by ammargitham** [comment]
Updating should not matter. Did you perhaps favorited any of these wallpapers and use favorites in your auto wallpaper?

**Comment by beast-14** [comment]
> Updating should not matter. Did you perhaps favorited any of these wallpapers and use favorites in your auto wallpaper?

No I did not try that actually

**Comment by ammargitham** [comment]
> No I did not try that actually
> Should I ?

No need. If it's working fine now then no problem. I will close this issue for now. If you face this issue again, feel free to reopen it.

**Comment by beast-14** [comment]
> > No I did not try that actually
> > Should I ?
> 
> No need. If it's working fine now then no problem. I will close this issue for now. If you face this issue again, feel free to reopen it.

Yaa sure ☺️

**Comment by beast-14** [comment]
> > No I did not try that actually
> > Should I ?
> 
> No need. If it's working fine now then no problem. I will close this issue for now. If you face this issue again, feel free to reopen it.

Bro I got it .. it happens when the phone is in landscape mode ..

**Comment by ammargitham** [comment]
Got it. Will try to delay setting the wallpaper when the phone is not in its default orientation.
