### ISSUE TITLE
Using `Activity` to change wallpaper displays full-screen overlay

### ISSUE THREAD

**Issue by KAGEYAM4** [ammargitham/WallFlow#56]
I am using `com.ammar.wallflow.plus/com.ammar.wallflow.activities.changewallpaper.ChangeWallpaperActivity`, to trigger wallpaper change using another app - `Xposed edge pro`. A full-screen overlay pops-up.

It would be make experiece better if it was either a `toast` or `notification` instead.

Here's a screenshot ->

![output](https://github.com/ammargitham/WallFlow/assets/75798544/798c53b8-5459-4a64-87ae-e23307061015)

**Comment by ammargitham** [comment]
Can you maybe use [the broadcast](https://github.com/ammargitham/WallFlow#broadcast-details-for-tasker-and-similar-apps) instead?

**Comment by KAGEYAM4** [comment]
> Can you maybe use [the broadcast](https://github.com/ammargitham/WallFlow#broadcast-details-for-tasker-and-similar-apps) instead?

Yes this works, Thank you.
