### ISSUE TITLE
Random toggle for auto wallpaper changer, different timers, different folders

### ISSUE THREAD

**Issue by beast-14** [ammargitham/WallFlow#57]
1. I request you to introduce a toggle which enables or disables the randomisation of wallpapers for all online, fav, and local.

This way same wallpaper won't come again and again because of randomisation and we will have the opportunity to experience the complete folder simultaneously which we have created.

2. Different timers for lock screen and homescreen wallpaper change.(if possible)

3. Allow selecting different local folders for lockscreen and homescreen wallpaper change

**Comment by ammargitham** [comment]
3rd point is covered by #51 

I had an idea for giving more control over the random wallpaper selection. Just need to give more thought to it.

**Comment by beast-14** [comment]
> 3rd point is covered by #51 
> 
> I had an idea for giving more control over the random wallpaper selection. Just need to give more thought to it.

And what about the 2nd point .. ? Is it possible or not

**Comment by ammargitham** [comment]
> And what about the 2nd point .. ? Is it possible or not

Yes, 2nd point should be possible too.
