### ISSUE TITLE
[Bug][2.3.1] autowallpaper does not update

### ISSUE THREAD

**Issue by julien-vu** [ammargitham/WallFlow#61]
Android: lineage 20, android 13

Issue: since 2.3.1 auto wallpaper do not change the wallpaper

Configuration:
- frequency: 15mn
- change lock and home with different wallpaper
- wallpaper from local folder

**Comment by ammargitham** [comment]
Have you set any constraints for the auto wallpaper? The auto wallpaper feature depends entirely on the OS to trigger it at the set interval. There is nothing the app can do to make it trigger exactly at that time. Only workaround would be to use alarmmanager, which would make the app work as an alarm, which I don't want to do.

Something I remember is that one person did face similar problem, and a reinstall fixed it. Maybe you can try the same.

**Comment by julien-vu** [comment]
It worked under 2.2.0 hence why I thought there was an issue

**Comment by ammargitham** [comment]
Hi. Are you still facing this issue?

**Comment by ammargitham** [comment]
@julien-vu Feel free to reopen this issue if you are still facing it.
