### ISSUE TITLE
Unable to scroll to bottom of favorites

### ISSUE THREAD

**Issue by WildManiac** [ammargitham/WallFlow#69]
I have more favorites than can show on screen, and am unable to view the very bottom of the list. Either the very bottom is cut off, or the items are completely hidden. You can see it in action in the video below:

https://github.com/ammargitham/WallFlow/assets/11233971/451b74a3-a3c7-4b79-a321-45310fcb6ebf

WallFlow Plus version: 2.3.1
Device: Samsung Galaxy A52 5G
OS: OneUI 6.0 (Android 14)

**Comment by ammargitham** [comment]
Fixed in 2.4.1
