### ISSUE TITLE
info and share button

### ISSUE THREAD

**Issue by personaingrata** [ammargitham/WallFlow#77]
with the 2.4.0 update the info and share buttons moved to the top, where they aren`t easily accesible with nowadays big smartphones.
please bring these buttons back to the bottom bar

**Comment by ammargitham** [comment]
If I bring both down, there'll be 6 actions in the bottom bar (including the 'apply wallpaper' action on the right). This is against the Material 3 guidelines and also could be a problem for smaller screens. How about I just put the info action down?

**Comment by personaingrata** [comment]
it's perfectly fine for me, if you put just the the info button down again. i appreciate it! thanks

**Comment by ammargitham** [comment]
Changed in 2.4.1
