### ISSUE TITLE
The build requires both jdk 11 and jdk 17

### ISSUE THREAD

**Issue by linsui** [ammargitham/WallFlow#81]
F-Droid recently upgraded the buildserver to Bookworm and jdk 11 is not installed anymore. Then I found that the build failed without jdk 11 thought jdk 17 is required to run gradle 8.

https://gitlab.com/fdroid/fdroiddata/-/jobs/6413647534
https://gitlab.com/fdroid/fdroiddata/-/jobs/6413647534

Is jdk 11 necessary? Could it be updated? Thanks!

**Comment by ammargitham** [comment]
Hi @linsui, I have pushed a45d3b520b64058969986e6a2d0bb1c1125b876d. Is it possible for you to check if this works without me creating a release?

**Comment by linsui** [comment]
It works, thanks! Will you update the apk of the current release or I should wait for the next version?

**Comment by ammargitham** [comment]
Great. I'll just push the next version. Maybe tomorrow.

**Comment by ammargitham** [comment]
Fixed by https://github.com/ammargitham/WallFlow/commit/a45d3b520b64058969986e6a2d0bb1c1125b876d

**Comment by linsui** [comment]
Thanks!
