### ISSUE TITLE
There is bug when using Pinch to zoom 

### ISSUE THREAD

**Issue by Scapy47** [ammargitham/WallFlow#86]
When zooming in the image wallpaper gets zoomed but in random direction and image gets out centre to upper or lower side of screen sometimes left and right

**Comment by ammargitham** [comment]
Can you attach a screen recording?

**Comment by Scapy47** [comment]
Sure 

https://github.com/ammargitham/WallFlow/assets/134828740/6d84b5a4-9442-4683-9aa1-71de1eddb2c6

**Comment by ammargitham** [comment]
@Scapy47 Please try the latest alpha to check if this issue is resolved.

**Comment by Scapy47** [comment]
It's fixed 👍

**Comment by scapy47** [comment]
Yes It's fixed 👍
