### ISSUE TITLE
Local Directory Bug

### ISSUE THREAD

**Issue by beast-14** [ammargitham/WallFlow#87]
When I am selecting a local directory for home screen, it's getting automatically selected to lock screen too and vice versa.

![Screenshot_2024-03-30-19-41-36-258_com.ammar.wallflow.plus.jpg](https://github.com/ammargitham/WallFlow/assets/145965285/bb00042d-a9d5-4939-a6fc-e52e3b58315a)

![Screenshot_2024-03-30-19-41-33-621_com.ammar.wallflow.plus.jpg](https://github.com/ammargitham/WallFlow/assets/145965285/56d1dffa-7a91-432f-857b-4e11c674f97b)

**Comment by irresistibl** [comment]
Somewhat related, but I'm getting an error where the app crashes whenever attempting to load the local directory in any of the settings.

Brand: samsung, Model: SM-N986B
Board: exynos990, Manufacturer: samsung
OS: 13

**Comment by ammargitham** [comment]
@irresistibl can you open another issue for your crash? As this issue is not crash related. Also it would be great if you could attach a crash log using [LogFox](https://f-droid.org/en/packages/com.f0x1d.logfox/).

**Comment by irresistibl** [comment]
Absolutely, @ammargitham. Creating a new issue now
