### ISSUE TITLE
"Wallpaper not changed: no wallpaper found" when trying to change wallpaper with favorites as source

### ISSUE THREAD

**Issue by Le0xFF** [ammargitham/WallFlow#90]
Hello and thank you for your work!

Before latest release I was able to easily change the wallpaper automatically by just saving them as favorites.
Starting from this morning, even if I have all of my favorotes still saved, when I click in "Change now", the app tells me "Wallpaper not changed: no wallpaper found".

If I add a new favorite, then I'm able to change the wallpaper with the "Change now" button.
If I remove it, then I'm not able to change wallpaper anymore.

Here's attached my setting and favorites, I hope it helps, but if anything more is needed, please let me know!

[wallflow_backup_20240416141631.json](https://github.com/ammargitham/WallFlow/files/14996996/wallflow_backup_20240416141631.json)

**Comment by beast-14** [comment]
This issue happened with me too ..I noticed it when there are 6-7 wallpapers in a folder and all get applied in sequence but after the last wallpaper, it says wallpaper not found and the wallpaper isn't changing anymore..

**Comment by ammargitham** [comment]
Will investigate this.

**Comment by Le0xFF** [comment]
Today I had again the "no wallpaper found" problem, but this time it was an easy fix.

The next wallpaper in line was gone, probably the post from reddit was deleted, and it gave me 404 error. If I tried to change the wallpaper manually, the app could not change it.
After removing the 404 wallpaper, the app was able again to change wallpaper to the next one in line.

**Comment by ammargitham** [comment]
Thanks for the report. Will take a look at that too.

**Comment by ammargitham** [comment]
@Le0xFF When you say you 'removed the wallpaper', do you mean you had this wallpaper in your favorites and you un-favorited it?

**Comment by Le0xFF** [comment]
Yes, that's correct. After removing it from my favourites, everything was working again.

I'll try to find the link again, but I don't think it will be easy 😔

**Comment by ammargitham** [comment]
Please try https://github.com/ammargitham/WallFlow/releases/tag/v2.6.0-alpha01 and let me know if this issue is fixed.

**Comment by beast-14** [comment]
> Please try https://github.com/ammargitham/WallFlow/releases/tag/v2.6.0-alpha01 and let me know if this issue is fixed.


Still the same .. it's happening after the last wallpaper in the folder. 


![Screenshot_2024-05-19-18-44-12-238_com.ammar.wallflow.plus.png](https://github.com/ammargitham/WallFlow/assets/145965285/aadd7ac3-2024-4854-89a2-50a0039d3bb2)

**Comment by ghost** [comment]
Hello, sorry for late reply. I didn't have the time to test the latest update, but just in case it can be still useful, here's a link to a 404 error!

https://www.reddit.com/r/Amoledbackgrounds/comments/1d3f3db/one_of_the_first_ever_walls_posted_on/

**Comment by jspkay** [comment]
I had the same problem... I downloaded v2.6.0-alpha01 and it seems to work well now!

Thank you for your amazing job! 😍
